server:
  port: 8080

spring:
  application:
    name: bankcards
  main:
    allow-circular-references: true
  
  datasource:
    url: jdbc:h2:mem:bankcards
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  liquibase:
    change-log: classpath:db/migration/changelog.xml
    enabled: false

jwt:
  secret: BankCardJwtSecretKey12345678901234567890
  expiration: 86400000 # 24 hours

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
